inherit_from: .rubocop_todo.yml

Metrics/ClassLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb
